service: product-service

frameworkVersion: 2

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    apiGateway:
        minimumCompressionSize: 1024
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
    getProductsList:
        handler: handlers/product-list.getProductsList
        events:
            - http:
                  method: get
                  path: products
                  cors: true

    getProductsById:
        handler: handlers/product-item.getProductsById
        events:
            - http:
                  method: get
                  path: products/{productId}
                  cors: true
