service: product-service

frameworkVersion: 2

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

plugins:
    - serverless-webpack
    - serverless-dotenv-plugin

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    apiGateway:
        minimumCompressionSize: 1024
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
    getProductsList:
        handler: handlers/product-list.getProductsList
        events:
            - http:
                  method: get
                  path: products
                  cors: true

    getProductsById:
        handler: handlers/product-item.getProductsById
        events:
            - http:
                  method: get
                  path: products/{productId}
                  cors: true

    createProducts:
        handler: handlers/product-item-create.createProducts
        events:
            - http:
                  method: post
                  path: products
                  cors: true

    updateProducts:
        handler: handlers/product-item-upsert.upsertProducts
        events:
            - http:
                  method: put
                  path: products
                  cors: true

    removeProducts:
        handler: handlers/product-item-delete.deleteProducts
        events:
            - http:
                  method: delete
                  path: products/{productId}
                  cors: true
