service: import-service

frameworkVersion: 2

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    apiGateway:
        minimumCompressionSize: 1024
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
        - Effect: "Allow"
          Action: "s3:ListBucket"
          Resources:
              - "arn:aws:s3:::pav-import-data"
        - Effect: "Allow"
              Action: "s3:*"
              Resources:
                  - "arn:aws:s3:::pav-import-data/*"

functions:
    importProductsFile:
        handler: handlers/import-products.importProductsFile
        events:
            - http:
                  method: get
                  path: import
                  cors: true
                  request:
                      parameters:
                          querystrings:
                              name: true
