service: import-service

frameworkVersion: 2

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: 
          forceExclude:
            - aws-sdk

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    apiGateway:
        minimumCompressionSize: 1024
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - 's3:ListBucket'
          Resource:
              - 'arn:aws:s3:::pav-import-data'
        - Effect: Allow
          Action:
              - 's3:*'
          Resource:
              - 'arn:aws:s3:::pav-import-data/*'

functions:
    importProductsFile:
        handler: handlers/import-products.importProductsFile
        events:
            - http:
                  method: get
                  path: import
                  cors: true
                  request:
                      parameters:
                          querystrings:
                              name: true
    importFileParser:
        handler: handlers/import-file.importFileParser
        events:
            - s3:
                  bucket: pav-import-data
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploaded/
                  existing: true
