service: import-service

frameworkVersion: 2

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    apiGateway:
        minimumCompressionSize: 1024
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        SQS_URL:
            Ref: SQSQueue
        SNS_ARN:
            Ref: SNSTopic
    iamRoleStatements:
        - Effect: Allow
          Action:
              - 's3:ListBucket'
          Resource:
              - 'arn:aws:s3:::pav-import-data'
        - Effect: Allow
          Action:
              - 's3:*'
          Resource:
              - 'arn:aws:s3:::pav-import-data/*'
        - Effect: Allow
          Action:
              - 'sqs:*'
          Resource:
              - Fn::GetAtt: [SQSQueue, Arn]
        - Effect: Allow
          Action:
              - 'sns:*'
          Resource:
              Ref: SNSTopic

resources:
    Resources:
        SQSQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: catalogItemsQueue
        SNSTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: createProductTopic
        SNSSubscription:
            Type: AWS::SNS::Subscription
            Properties:
                Endpoint: dobrenko92@gmail.com
                Protocol: email
                TopicArn:
                    Ref: SNSTopic

functions:
    importProductsFile:
        handler: handlers/import-products.importProductsFile
        events:
            - http:
                  method: get
                  path: import
                  cors: true
                  request:
                      parameters:
                          querystrings:
                              name: true

    importFileParser:
        handler: handlers/import-file.importFileParser
        events:
            - s3:
                  bucket: pav-import-data
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploaded/
                  existing: true

    catalogBatchProcess:
        handler: handlers/import-batch-process.catalogBatchProcess
        events:
            - sqs:
                  batchSize: 5
                  arn:
                      Fn::GetAtt:
                          - SQSQueue
                          - Arn
